default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  
  username: postgres

development:
  <<: *default
  database: ccb_tracker_development

test:
  <<: *default
  database: ccb_tracker_test

production:
  <<: *default
  database: ccb_tracker_production
  username: ccb_tracker
  password: <%= ENV['CCB_TRACKER_DATABASE_PASSWORD'] %>
